package Utils;

import com.example.pixel_effect_app.R;

public class Ulits {

    public static int img[] = {R.drawable.bg_3d_1_black,
            R.drawable.bg_3d_3_black,
            R.drawable.bg_3d_4_black,
            R.drawable.bg_3d_5_black,
            R.drawable.bg_3d_6_black,
            R.drawable.splash_01,
            R.drawable.splash_02,
            R.drawable.splash_03,
            R.drawable.splash_04,
            R.drawable.splash_05,
            R.drawable.splash_06,
            R.drawable.pixel_mask_1,
            R.drawable.pixel_mask_2};

    public static int imges_Effect[] = {R.drawable.pixel_01,
            R.drawable.pixel_2,
            R.drawable.pixel_02,
            R.drawable.pixel_3,
            R.drawable.pixel_03,
            R.drawable.pixel_4,
            R.drawable.pixel_04,
            R.drawable.pixel_05,
            R.drawable.pixel_6,
            R.drawable.pixel_06,
            R.drawable.pixel_7,
            R.drawable.pixel_8,
            R.drawable.pixel_9,
            R.drawable.pixel_13,
            R.drawable.pixel_14,
            R.drawable.pixel_15,
            R.drawable.pixel_16,
            R.drawable.pixel_17,
            R.drawable.pixel_18,
            R.drawable.pixel_19,
            R.drawable.pixel_20,
            R.drawable.pixel_21,
            R.drawable.pixel_22,
            R.drawable.pixel_23,
            R.drawable.pixel_24,
            R.drawable.pixel_25,
            R.drawable.pixel_26,
            R.drawable.pixel_27,
            R.drawable.pixel_28};

    public static int imges_Glare[] = {R.drawable.flare_01,
            R.drawable.flare_02,
            R.drawable.flare_03,
            R.drawable.flare_04,
            R.drawable.flare_05,
            R.drawable.flare_06};


    public static int s1[] = {R.drawable.a1,
            R.drawable.a2,
            R.drawable.a3,
            R.drawable.a4,
            R.drawable.a6,
            R.drawable.a7,
            R.drawable.a8,
            R.drawable.a9,
            R.drawable.a10,
            R.drawable.a12,
            R.drawable.a14,
            R.drawable.a15,
            R.drawable.a16,
            R.drawable.a17,
            R.drawable.a18,
            R.drawable.a19,
            R.drawable.a20,
            R.drawable.a21,
            R.drawable.a22,
            R.drawable.a24,
            R.drawable.a25,
            R.drawable.a26,
            R.drawable.a28,
            R.drawable.a29,
            R.drawable.a30,
            R.drawable.a32,};

}
